### ISSUE TITLE
Hy friend can u help me

### ISSUE THREAD

**Issue by Venomhash123** [prajwalan364/hotstar-dl#1]

**Comment by prajwalan364** [comment]
Yes tell me

**Comment by prajwalan364** [comment]
> _No description provided._

yes tell me

**Comment by Venomhash123** [comment]
Ur script not work

**Comment by Venomhash123** [comment]
Can u help me or give me anOther working hotstar repo

**Comment by prajwalan364** [comment]
> Ur script not work

may be they made some changes in the website

**Comment by prajwalan364** [comment]
> Can u help me or give me anOther working hotstar repo

ill try

**Comment by prajwalan364** [comment]
> > Can u help me or give me anOther working hotstar repo
> 
> ill try

check now

**Comment by Venomhash123** [comment]
What problem bro 
![Screenshot_2021-11-08-20-43-41-519_com termux](https://user-images.githubusercontent.com/89146099/140767732-6c1a4ff7-6f7d-44a1-98fb-cbb307c33e89.jpg)

**Comment by prajwalan364** [comment]
i think url format  is wrong
url should like this: `https://www.hotstar.com/in/movies/hum-do-hamare-do/1260072216`

**premium movies are not going to work
only free movies can be downloaded**

better try on linux or windows

**Comment by Venomhash123** [comment]
Bro I have no pc😔😔😔😔

Bro is this link is right????-----https://www.hotstar.com/in/a-new-room-for-anupama/1260065981


If not then how get right link



If this link is right  then same problem occurs
![Screenshot_2021-11-08-23-49-15-653_com termux](https://user-images.githubusercontent.com/89146099/140796411-e9a35159-ef9a-49fe-af48-a3acdf673648.jpg)

**Comment by Venomhash123** [comment]
Can u give me ur  telegram id for bettter help

**Comment by prajwalan364** [comment]
> Can u give me ur telegram id for bettter help

https://t.me/prajwalan364
